/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CollectionRouteImport } from './routes/collection'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as TradeRouteImport } from './routes/trade'
import { Route as WantedRouteImport } from './routes/wanted'
import { Route as DeckSplatRouteImport } from './routes/deck.$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionRoute = CollectionRouteImport.update({
  id: '/collection',
  path: '/collection',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TradeRoute = TradeRouteImport.update({
  id: '/trade',
  path: '/trade',
  getParentRoute: () => rootRouteImport,
} as any)
const WantedRoute = WantedRouteImport.update({
  id: '/wanted',
  path: '/wanted',
  getParentRoute: () => rootRouteImport,
} as any)
const DeckSplatRoute = DeckSplatRouteImport.update({
  id: '/deck/$',
  path: '/deck/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/collection': typeof CollectionRoute
  '/settings': typeof SettingsRoute
  '/trade': typeof TradeRoute
  '/wanted': typeof WantedRoute
  '/deck/$': typeof DeckSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/collection': typeof CollectionRoute
  '/settings': typeof SettingsRoute
  '/trade': typeof TradeRoute
  '/wanted': typeof WantedRoute
  '/deck/$': typeof DeckSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/collection': typeof CollectionRoute
  '/settings': typeof SettingsRoute
  '/trade': typeof TradeRoute
  '/wanted': typeof WantedRoute
  '/deck/$': typeof DeckSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/collection' | '/settings' | '/trade' | '/wanted' | '/deck/$'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/collection' | '/settings' | '/trade' | '/wanted' | '/deck/$'
  id:
    | '__root__'
    | '/'
    | '/collection'
    | '/settings'
    | '/trade'
    | '/wanted'
    | '/deck/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CollectionRoute: typeof CollectionRoute
  SettingsRoute: typeof SettingsRoute
  TradeRoute: typeof TradeRoute
  WantedRoute: typeof WantedRoute
  DeckSplatRoute: typeof DeckSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collection': {
      id: '/collection'
      path: '/collection'
      fullPath: '/collection'
      preLoaderRoute: typeof CollectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trade': {
      id: '/trade'
      path: '/trade'
      fullPath: '/trade'
      preLoaderRoute: typeof TradeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wanted': {
      id: '/wanted'
      path: '/wanted'
      fullPath: '/wanted'
      preLoaderRoute: typeof WantedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deck/$': {
      id: '/deck/$'
      path: '/deck/$'
      fullPath: '/deck/$'
      preLoaderRoute: typeof DeckSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CollectionRoute: CollectionRoute,
  SettingsRoute: SettingsRoute,
  TradeRoute: TradeRoute,
  WantedRoute: WantedRoute,
  DeckSplatRoute: DeckSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
